export const FETCH_ITEMS = "FETCH_ITEMS";
export const FETCH_ITEM = "FETCH_ITEM";
export const FETCH_ORDERS = "FETCH_ORDERS";

export const SET_ORDER_FILTER = "SET_ORDER_FILTER";
export const REMOVE_ORDER_FILTER = "REMOVE_ORDER_FILTER";
export const SET_USER_FILTER = "SET_USER_FILTER";
export const REMOVE_USER_FILTER = "REMOVE_USER_FILTER";